---

- name: OS-specific packages
  package:
    name: "{{ consul_distro_packages }}"
    state: "{{ consul_package_state }}"
    update_cache: "{{ (ansible_pkg_mgr == 'apt') | ternary('yes', omit) }}"
    cache_valid_time: "{{ (ansible_pkg_mgr == 'apt') | ternary(cache_timeout, omit) }}"
  register: install_packages
  until: install_packages is success
  retries: 5
  delay: 2
  tags:
    - install-apt
    - install-yum
    - install-zypper

###########################
# Recuperation du binaire

- name: Install consul
  when: install_consul == true
  block:
    - name: Get binary ({{ version_to_install }})
      get_url:
        url: "{{ consul_consul_repo_url }}/{{ version_to_install }}/consul_{{ version_to_install }}_linux_amd64.zip"
        dest: "/tmp/consul_bin.zip"
      environment:
        http_proxy: "{{ consul_http_proxy }}"
        https_proxy: "{{ consul_https_proxy }}"

    - name: Install binary
      unarchive: src="/tmp/consul_bin.zip" dest=/usr/local/bin/ mode=0755 copy=no
      notify: restart consul

    - name: Cleanup
      file: path="/tmp/consul_bin.zip" state=absent

#############################################
# Création des répertoires et service systemd

- name: Directories
  file: path={{ item }} state=directory
  with_items:
    - /etc/consul.d
    - /var/lib/consul

- name: Systemd services
  notify: reload systemd
  template: src=consul.service.j2 dest=/etc/systemd/system/consul.service
