- name: Post-Install Token | Show master token
  run_once: true
  when:
  - consul_show_master_token | lower =='true'
  - acl_info.stdout.find("no longer") < 0
  debug: var=acl_secret_id

# TODO: set a local fact in pre_install to manage this
- name: Post-Install Token | Create an env file containing the token
  when:
  - write_consul_env_file | lower == 'true'
  block:
  - name: Post-Install Token | Create .consul.env
    file:
      path: "{{ lookup('env', 'HOME') }}/.consul.env"
      state: touch

  - name: Post-Install Token | Create an env file containing the token
    lineinfile:
      path: "{{ lookup('env', 'HOME') }}/.consul.env"
      state: present
      regexp: ^(CONSUL_HTTP_TOKEN=.+){0,1}$
      line: CONSUL_HTTP_TOKEN={{ acl_secret_id }}

- name: Post-Install Token | Create a swift object containing the token
  when:
  - consul_acl_token_store_swift | lower == 'true'
  shell: echo {{ acl_secret_id }} | swift upload --object-name=token consul -

