- name: restart consul
  service: name=consul state=restarted enabled=yes

- name: reload systemd
  systemd: daemon_reload=yes

- name: restart telegraf
  service: name=telegraf state=restarted
  when: telegraf_service.stdout.find('inactive') < 0
